/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanıcının tüm hesaplarını listeler */
        get: operations["AccountController_findAll"];
        put?: never;
        /** Yeni bir hesap oluşturur */
        post: operations["AccountController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tek bir hesabın detaylarını ID ile getirir */
        get: operations["AccountController_findOne"];
        put?: never;
        post?: never;
        /** Kayıt silinir (Soft Delete ile arşivlenir) */
        delete: operations["AccountController_remove"];
        options?: never;
        head?: never;
        /** Hesap bilgilerini günceller (Sadece gönderilen alanlar değişir) */
        patch: operations["AccountController_update"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kategorileri listeler (Türe göre filtrelenebilir) */
        get: operations["CategoryController_findAll"];
        put?: never;
        /** Yeni bir kategori oluşturur */
        post: operations["CategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tek bir kategoriyi ID ile getirir */
        get: operations["CategoryController_findOne"];
        put?: never;
        post?: never;
        /** Kayıt silinir (Soft Delete ile arşivlenir) */
        delete: operations["CategoryController_remove"];
        options?: never;
        head?: never;
        /** Kategori bilgilerini günceller */
        patch: operations["CategoryController_update"];
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tüm işlemleri liste halinde getirir (Gelişmiş Sayfalama ve Filtreleme içerir) */
        get: operations["TransactionController_findAll"];
        put?: never;
        /** Yeni bir gelir, gider veya transfer ekler (Taksit destekli) */
        post: operations["TransactionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanıcının düzenli ödemelerini listeler */
        get: operations["TransactionController_findRecurring"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/recurring/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Düzenli bir ödemeyi iptal eder */
        delete: operations["TransactionController_cancelRecurring"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/installments/{installmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Bir taksit grubunu (Tüm ayları) tamamen iptal eder/siler */
        delete: operations["TransactionController_deleteInstallmentGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Tek bir işlemi siler (Peşin işlemler veya tekil taksitler için) */
        delete: operations["TransactionController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** İşlem listesini filtrelere göre Excel dosyası olarak indirir */
        get: operations["TransactionController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanicinin planli odemelerini listeler */
        get: operations["PlannedPaymentController_findAll"];
        put?: never;
        /** Yeni planli odeme olusturur */
        post: operations["PlannedPaymentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tek bir planli odeme detayini getirir */
        get: operations["PlannedPaymentController_findOne"];
        put?: never;
        post?: never;
        /** Planli odeme kaydini soft delete ile arsivler */
        delete: operations["PlannedPaymentController_remove"];
        options?: never;
        head?: never;
        /** Planli odeme kaydini gunceller */
        patch: operations["PlannedPaymentController_update"];
        trace?: never;
    };
    "/planned-payments/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Planli odemeyi odendi olarak isaretler ve gider islemi olusturur */
        patch: operations["PlannedPaymentController_pay"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanicinin bildirimlerini listeler */
        get: operations["NotificationController_findAll"];
        put?: never;
        /** Manuel bildirim olusturur */
        post: operations["NotificationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tum okunmamis bildirimleri okundu yapar */
        patch: operations["NotificationController_markAllAsRead"];
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tek bir bildirimi getirir */
        get: operations["NotificationController_findOne"];
        put?: never;
        post?: never;
        /** Bildirimi soft delete ile arsivler */
        delete: operations["NotificationController_remove"];
        options?: never;
        head?: never;
        /** Bildirim kaydini gunceller */
        patch: operations["NotificationController_update"];
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tek bildirimi okundu olarak isaretler */
        patch: operations["NotificationController_markAsRead"];
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seçili ay ve yıla ait bütçe özetini getirir */
        get: operations["DashboardController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/financial-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanıcının 100 üzerinden finansal sağlık skorunu hesaplar */
        get: operations["DashboardController_getHealthScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sistemdeki tüm etiketleri alfabetik olarak getirir */
        get: operations["TagController_findAll"];
        put?: never;
        /** Yeni bir etiket oluşturur (Otomatik küçük harfe çevirir) */
        post: operations["TagController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tekil etiket detayı getirir */
        get: operations["TagController_findOne"];
        put?: never;
        post?: never;
        /** Kayıt silinir (Soft Delete ile arşivlenir) */
        delete: operations["TagController_remove"];
        options?: never;
        head?: never;
        /** Etiket adını günceller */
        patch: operations["TagController_update"];
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tüm hedefleri ilerleme durumlarıyla birlikte listeler */
        get: operations["GoalController_findAll"];
        put?: never;
        /** Yeni bir tasarruf hedefi (kumbara) oluşturur */
        post: operations["GoalController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GoalController_findOne"];
        put?: never;
        post?: never;
        /** Kayıt silinir (Soft Delete ile arşivlenir) */
        delete: operations["GoalController_remove"];
        options?: never;
        head?: never;
        /** Hedef bilgilerini günceller */
        patch: operations["GoalController_update"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Giriş yapan kullanıcının bilgilerini getirir (FREE dahil herkes) */
        get: operations["UserController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/vip-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gelişmiş raporları getirir (Sadece PLUS/ADMIN paketi için) */
        get: operations["UserController_getVipReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yeni kullanıcı kaydı oluşturur */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sisteme giriş yapar ve JWT Token döner */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateAccountDto: {
            /**
             * @description Hesabın veya kişinin adı
             * @example Ziraat Maaş Hesabı
             */
            name: string;
            /**
             * @example BANK
             * @enum {string}
             */
            type: "BANK" | "CREDIT_CARD" | "CASH" | "PERSON";
            /**
             * @example TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR" | "GOLD";
            /**
             * @description Ekstre kesim günü (Sadece kredi kartları için)
             * @example 15
             */
            statementDay?: number;
            /**
             * @description Son ödeme günü (Sadece kredi kartları için)
             * @example 25
             */
            dueDay?: number;
        };
        AccountResponseDto: {
            /**
             * @description Hesabın benzersiz ID numarası
             * @example uuid-string
             */
            id: string;
            /**
             * @description Hesabın adı
             * @example Garanti Maaş Hesabı
             */
            name: string;
            /**
             * @description Hesap Tipi (Nakit, Banka, Kredi Kartı vb.)
             * @example BANK
             * @enum {string}
             */
            type: "BANK" | "CREDIT_CARD" | "CASH" | "PERSON";
            /**
             * @description Hesaptaki güncel bakiye
             * @example 15500.5
             */
            balance: number;
            /**
             * @description Para Birimi (TRY, USD, EUR, GOLD)
             * @example TRY
             */
            currency: string;
            /**
             * @description Kredi kartları için hesap kesim günü (Ayın kaçıncı günü)
             * @example 15
             */
            statementDay?: number;
            /**
             * @description Kredi kartları için son ödeme günü (Ayın kaçıncı günü)
             * @example 25
             */
            dueDay?: number;
            /**
             * Format: date-time
             * @description Hesabın sisteme eklenme tarihi
             * @example 2026-03-18T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Hesap bilgilerinin son güncellenme tarihi
             * @example 2026-03-18T15:30:00Z
             */
            updatedAt: string;
        };
        UpdateAccountDto: {
            /**
             * @description Hesabın veya kişinin adı
             * @example Ziraat Maaş Hesabı
             */
            name?: string;
            /**
             * @example BANK
             * @enum {string}
             */
            type?: "BANK" | "CREDIT_CARD" | "CASH" | "PERSON";
            /**
             * @example TRY
             * @enum {string}
             */
            currency?: "TRY" | "USD" | "EUR" | "GOLD";
            /**
             * @description Ekstre kesim günü (Sadece kredi kartları için)
             * @example 15
             */
            statementDay?: number;
            /**
             * @description Son ödeme günü (Sadece kredi kartları için)
             * @example 25
             */
            dueDay?: number;
        };
        BaseDeleteResponseDto: {
            /**
             * @description İşlemin başarı durumu
             * @example true
             */
            success: boolean;
            /**
             * @description Silinen/Arşivlenen kaydın ID numarası
             * @example uuid-string
             */
            id: string;
            /**
             * Format: date-time
             * @description Arşivlenme tarihi (Soft Delete)
             * @example 2026-03-23T20:14:00Z
             */
            deletedAt: string;
            /**
             * @description Kullanıcıya gösterilecek mesaj
             * @example Kayıt başarıyla arşivlendi.
             */
            message: string;
        };
        CreateCategoryDto: {
            /**
             * @description Category name
             * @example Market
             */
            name: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE" | "TRANSFER";
            /**
             * @description Emoji or icon representation
             * @example 🛒
             */
            icon?: string;
            /**
             * @description Hex color code
             * @example #FF0000
             */
            color?: string;
            /**
             * @description Bu kategori için aylık harcama limiti
             * @example 5000
             */
            monthlyLimit?: number;
        };
        CategoryResponseDto: {
            /** @example uuid-string */
            id: string;
            /** @example Market Alışverişi */
            name: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE" | "TRANSFER";
            /**
             * @description Kategori ikonu
             * @example 🛒
             */
            icon: string;
            /**
             * @description Kategori rengi
             * @example #FF5733
             */
            color: string;
            /**
             * @description Aylık bütçe limiti
             * @example 5000
             */
            monthlyLimit?: number;
            /**
             * Format: date-time
             * @example 2026-03-18T12:00:00Z
             */
            createdAt: string;
        };
        UpdateCategoryDto: {
            /**
             * @description Category name
             * @example Market
             */
            name?: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type?: "INCOME" | "EXPENSE" | "TRANSFER";
            /**
             * @description Emoji or icon representation
             * @example 🛒
             */
            icon?: string;
            /**
             * @description Hex color code
             * @example #FF0000
             */
            color?: string;
            /**
             * @description Bu kategori için aylık harcama limiti
             * @example 5000
             */
            monthlyLimit?: number;
        };
        CreateTransactionDto: {
            /**
             * @description Transaction amount
             * @example 150.5
             */
            amount: number;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE" | "TRANSFER";
            /**
             * @description Whether this transaction should be scheduled as recurring
             * @example false
             */
            isRecurring?: boolean;
            /**
             * @description Cron expression for recurring schedule (required when isRecurring is true)
             * @example 0 9 * * 1
             */
            cronExpression?: Record<string, never>;
            /**
             * @description Next execution timestamp for recurring schedule (required when isRecurring is true)
             * @example 2026-04-15T09:00:00Z
             */
            nextExecutionDate?: Record<string, never>;
            /**
             * @description Optional description
             * @example Haftalık market alışverişi
             */
            description?: string;
            /**
             * @description Taksit Sayısı (Peşin işlemler için boş bırakın)
             * @example 6
             */
            installmentCount?: number;
            /**
             * @description Kaç ay sonra ödenmeye başlanacak? (0: Bu ay, 1: Gelecek ay/Kredi Kartı mantığı)
             * @example 1
             */
            delayMonths?: number;
            /**
             * @description Transaction date (ISO 8601)
             * @example 2026-03-14T12:00:00Z
             */
            date: string;
            /**
             * @description Category ID
             * @example uuid-of-category
             */
            categoryId: string;
            /**
             * @description Account ID
             * @example uuid-of-account
             */
            accountId: string;
            /**
             * @description Target Account ID for transfers
             * @example uuid-of-target-account
             */
            toAccountId?: string;
            /**
             * @description Eğer bu işlem bir hedefe (kumbaraya) aktarılıyorsa hedefin ID'si
             * @example uuid-of-goal
             */
            goalId?: string;
            /**
             * @description İşleme eklenecek etiketlerin listesi (Varsa veritabanından bulur, yoksa yeni yaratır)
             * @example [
             *       "tatil",
             *       "yemek",
             *       "bodrum"
             *     ]
             */
            tags?: string[];
            /** @description Eğer bu işlem bütçe limitini aşıyorsa dönen akıllı sistem uyarısı */
            warningMessage?: string;
        };
        SimpleAccountDto: {
            /**
             * @description Hesap ID
             * @example uuid-string
             */
            id: string;
            /**
             * @description Hesap Adı
             * @example Garanti Maaş Hesabı
             */
            name: string;
            /**
             * @description Hesap Tipi (CASH, CREDIT_CARD vb.)
             * @example CASH
             */
            type: string;
            /**
             * @description Para Birimi
             * @example TRY
             */
            currency: string;
        };
        SimpleCategoryDto: {
            /**
             * @description Kategori ID
             * @example uuid-string
             */
            id: string;
            /**
             * @description Kategori Adı
             * @example Market Alışverişi
             */
            name: string;
            /**
             * @description Kategori İkonu
             * @example 🛒
             */
            icon: string;
            /**
             * @description Kategori Rengi
             * @example #FF5733
             */
            color: string;
        };
        SimpleGoalDto: {
            /**
             * @description Hedef ID
             * @example uuid-string
             */
            id: string;
            /**
             * @description Hedef Adı
             * @example Yaz Tatili
             */
            name: string;
        };
        SimpleTagDto: {
            /**
             * @description Etiket ID
             * @example uuid-string
             */
            id: string;
            /**
             * @description Etiket Adı
             * @example haftasonu
             */
            name: string;
        };
        TransactionResponseDto: {
            /**
             * @description İşlemin benzersiz ID numarası
             * @example uuid-string
             */
            id: string;
            /**
             * @description İşlem tutarı
             * @example 150.5
             */
            amount: number;
            /**
             * @description İşlem Tipi
             * @example EXPENSE
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE" | "TRANSFER";
            /**
             * @description Kullanıcının girdiği açıklama
             * @example Migros haftalık alışveriş
             */
            description?: string;
            /**
             * Format: date-time
             * @description İşlemin yapıldığı tarih
             * @example 2026-03-18T12:00:00Z
             */
            date: string;
            /**
             * @description İşlemin tekrarlayan (düzenli) ödeme olup olmadığı
             * @example false
             */
            isRecurring: boolean;
            /**
             * @description Tekrarlayan işlemler için cron ifadesi
             * @example 0 9 * * 1
             */
            cronExpression?: Record<string, never> | null;
            /**
             * @description Bir sonraki çalıştırma tarihi
             * @example 2026-04-15T09:00:00Z
             */
            nextExecutionDate?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Kredi kartı vb. durumlar için ekstre/ödeme tarihi
             * @example 2026-04-25T12:00:00Z
             */
            billingDate?: string;
            /**
             * @description Taksitli işlemleri birbirine bağlayan grup ID
             * @example uuid-installment-group
             */
            installmentId?: string;
            /**
             * @description Taksit bilgisi (Örn: 1. taksit, toplam 3 taksit)
             * @example 1/3
             */
            installmentInfo?: string;
            /** @description İşlemin yapıldığı hesap */
            account: components["schemas"]["SimpleAccountDto"];
            /** @description Eğer transfer işlemiyse, paranın gittiği hedef hesap */
            toAccount?: components["schemas"]["SimpleAccountDto"];
            /** @description İşlemin kategorisi */
            category: components["schemas"]["SimpleCategoryDto"];
            /** @description Eğer işlem bir kumbaraya para atma işlemiyse, o hedefin bilgisi */
            goal?: components["schemas"]["SimpleGoalDto"];
            /** @description İşleme atanmış etiketler (Hashtags) */
            tags?: components["schemas"]["SimpleTagDto"][];
            /**
             * Format: date-time
             * @description Kaydın oluşturulma zamanı
             * @example 2026-03-18T12:00:00Z
             */
            createdAt: string;
        };
        CreatePlannedPaymentDto: {
            /**
             * @description Planli odemenin basligi
             * @example Elektrik Faturasi
             */
            title: string;
            /**
             * @description Planli odeme tutari
             * @example 1250.5
             */
            amount: number;
            /**
             * @description Son odeme tarihi (ISO 8601)
             * @example 2026-05-01
             */
            dueDate: string;
            /**
             * @description Planli odeme tipi
             * @example BILL
             * @enum {string}
             */
            type: "CREDIT_CARD" | "BILL" | "CUSTOM";
            /**
             * @description Opsiyonel olarak odemenin yapilacagi hesap ID
             * @example f5f6c85d-81a0-443d-b163-95de12604709
             */
            accountId?: string;
            /**
             * @description Kategori ID
             * @example d1ac3b6c-6d61-4f7a-96cb-8055e57cabdd
             */
            categoryId: string;
        };
        PlannedPaymentResponseDto: {
            /** @example a55a4d46-423c-4e4f-9358-8b188f5de8ce */
            id: string;
            /** @example Su Faturasi */
            title: string;
            /** @example 500 */
            amount: number;
            /**
             * Format: date-time
             * @example 2026-05-10
             */
            dueDate: string;
            /** @example false */
            isPaid: boolean;
            /**
             * @example BILL
             * @enum {string}
             */
            type: "CREDIT_CARD" | "BILL" | "CUSTOM";
            /** @example 71f3f870-6fd4-4408-bbab-cfdd21e86f7a */
            accountId?: Record<string, never>;
            /** @example ca1f774b-2fca-4095-b13f-8545c9bead7f */
            categoryId: string;
            /**
             * Format: date-time
             * @example 2026-04-15T09:30:00.000Z
             */
            createdAt: string;
        };
        UpdatePlannedPaymentDto: {
            /**
             * @description Planli odemenin basligi
             * @example Elektrik Faturasi
             */
            title?: string;
            /**
             * @description Planli odeme tutari
             * @example 1250.5
             */
            amount?: number;
            /**
             * @description Son odeme tarihi (ISO 8601)
             * @example 2026-05-01
             */
            dueDate?: string;
            /**
             * @description Planli odeme tipi
             * @example BILL
             * @enum {string}
             */
            type?: "CREDIT_CARD" | "BILL" | "CUSTOM";
            /**
             * @description Opsiyonel olarak odemenin yapilacagi hesap ID
             * @example f5f6c85d-81a0-443d-b163-95de12604709
             */
            accountId?: string;
            /**
             * @description Kategori ID
             * @example d1ac3b6c-6d61-4f7a-96cb-8055e57cabdd
             */
            categoryId?: string;
        };
        CreateNotificationDto: {
            /** @example Son odeme tarihi yaklasiyor! */
            title: string;
            /** @example Elektrik faturanizin son odeme tarihi 2 gun sonra. */
            message: string;
            /**
             * @example MEDIUM_YELLOW
             * @enum {string}
             */
            urgency: "LOW_GREEN" | "MEDIUM_YELLOW" | "CRITICAL_RED";
            /**
             * @description Bagli oldugu planli odeme ID
             * @example c42f42e1-6472-486a-8cc6-9bc1cf7a2d76
             */
            referenceId?: string;
        };
        NotificationResponseDto: {
            /** @example 1a0978f7-c1ca-45f2-bf15-8ca7358d2dc6 */
            id: string;
            /** @example Odemeniz gecikmekte! */
            title: string;
            /** @example Kredi karti odemenizin son tarihi gecmis durumda. */
            message: string;
            /**
             * @example CRITICAL_RED
             * @enum {string}
             */
            urgency: "LOW_GREEN" | "MEDIUM_YELLOW" | "CRITICAL_RED";
            /** @example false */
            isRead: boolean;
            /** @example 6f3335e9-1221-4908-a6d5-6209ec2e0877 */
            referenceId?: Record<string, never>;
            /**
             * Format: date-time
             * @example 2026-04-15T08:00:00.000Z
             */
            createdAt: string;
        };
        UpdateNotificationDto: {
            /** @example Son odeme tarihi yaklasiyor! */
            title?: string;
            /** @example Elektrik faturanizin son odeme tarihi 2 gun sonra. */
            message?: string;
            /**
             * @example MEDIUM_YELLOW
             * @enum {string}
             */
            urgency?: "LOW_GREEN" | "MEDIUM_YELLOW" | "CRITICAL_RED";
            /**
             * @description Bagli oldugu planli odeme ID
             * @example c42f42e1-6472-486a-8cc6-9bc1cf7a2d76
             */
            referenceId?: string;
        };
        HealthSummaryDto: {
            /**
             * @description Bu ayki toplam gelir
             * @example 50000
             */
            totalIncome: number;
            /**
             * @description Bu ayki toplam harcama
             * @example 15000
             */
            totalExpense: number;
            /**
             * @description Bu ay kumbaraya atılan toplam miktar
             * @example 5000
             */
            totalSavings: number;
            /**
             * @description Kredi kartından yapılan harcama tutarı
             * @example 4500
             */
            creditCardExpense: number;
        };
        ScoreBreakdownDto: {
            /**
             * @description Gelir/Gider oranından alınan puan (Max 40)
             * @example 40
             */
            incomeExpenseRatio: number;
            /**
             * @description Birikim alışkanlığından alınan puan (Max 30)
             * @example 30
             */
            savingsHabit: number;
            /**
             * @description Kredi kartı kullanımından alınan puan (Max 20)
             * @example 20
             */
            creditCardUsage: number;
            /**
             * @description Nakit durumundan alınan puan (Max 10)
             * @example 10
             */
            cashHealth: number;
        };
        FinancialAdviceDto: {
            /**
             * @description Çeviri (i18n) için anahtar kod
             * @example SUCCESS_EXCELLENT_HEALTH
             */
            code: string;
            /**
             * @description Kullanıcıya gösterilecek varsayılan mesaj
             * @example 🏆 Harika gidiyorsun! Finansal disiplinin mükemmel seviyede.
             */
            message: string;
        };
        FinancialHealthResponseDto: {
            /**
             * @description 100 üzerinden toplam finansal sağlık skoru
             * @example 85
             */
            totalScore: number;
            /**
             * @description Durum kodu (i18n çevirileri için)
             * @example STATUS_EXCELLENT
             */
            statusCode: string;
            /**
             * @description Skorun metinsel karşılığı (Varsayılan)
             * @example Mükemmel
             */
            healthStatus: string;
            /** @description Harcama ve gelirlerin genel özeti */
            summary: components["schemas"]["HealthSummaryDto"];
            /** @description Puanların hangi kriterlerden alındığının detayı */
            scoreBreakdown: components["schemas"]["ScoreBreakdownDto"];
            /** @description Kullanıcıya özel üretilen finansal tavsiyeler listesi */
            advices: components["schemas"]["FinancialAdviceDto"][];
        };
        CreateTagDto: {
            /** @example tatil */
            name: string;
        };
        TagResponseDto: {
            /** @example uuid-string */
            id: string;
            /** @example haftasonu */
            name: string;
            /**
             * Format: date-time
             * @example 2026-03-18T12:00:00Z
             */
            createdAt: string;
        };
        UpdateTagDto: {
            /** @example tatil */
            name?: string;
        };
        CreateGoalDto: {
            /**
             * @description Hedefin adı
             * @example Yeni Nesil Macbook Pro
             */
            name: string;
            /**
             * @description Ulaşılmak istenen toplam tutar
             * @example 85000
             */
            targetAmount: number;
            /**
             * @description Başlangıçta kumbaraya atılacak tutar (Varsayılan: 0)
             * @example 0
             */
            currentAmount?: number;
            /**
             * @description Para birimi (Varsayılan: TRY)
             * @example TRY
             * @enum {string}
             */
            currency?: "TRY" | "USD" | "EUR" | "GOLD";
            /**
             * @description Hedefi temsil eden emoji/ikon
             * @example 💻
             */
            icon?: string;
            /**
             * @description Arayüzde gösterilecek renk (Hex)
             * @example #33FF57
             */
            color?: string;
        };
        GoalResponseDto: {
            /** @example uuid-string */
            id: string;
            /**
             * @description Hedefin adı
             * @example Yeni Nesil Macbook Pro
             */
            name: string;
            /**
             * @description Ulaşılmak istenen toplam tutar
             * @example 85000
             */
            targetAmount: number;
            /**
             * @description Şu ana kadar biriken tutar
             * @example 12500
             */
            currentAmount: number;
            /**
             * @description Para birimi
             * @example TRY
             */
            currency: string;
            /**
             * @description Hedef ikonu
             * @example 💻
             */
            icon: Record<string, never>;
            /**
             * @description Hedef rengi
             * @example #33FF57
             */
            color: Record<string, never>;
            /**
             * @description Yüzde kaçı tamamlandı?
             * @example 14.7
             */
            percentage: number;
            /**
             * @description Hedefe ulaşıldı mı?
             * @example false
             */
            isCompleted: boolean;
            /**
             * Format: date-time
             * @example 2026-03-18T12:00:00Z
             */
            createdAt: string;
        };
        UpdateGoalDto: {
            /**
             * @description Hedefin adı
             * @example Yeni Nesil Macbook Pro
             */
            name?: string;
            /**
             * @description Ulaşılmak istenen toplam tutar
             * @example 85000
             */
            targetAmount?: number;
            /**
             * @description Başlangıçta kumbaraya atılacak tutar (Varsayılan: 0)
             * @example 0
             */
            currentAmount?: number;
            /**
             * @description Para birimi (Varsayılan: TRY)
             * @example TRY
             * @enum {string}
             */
            currency?: "TRY" | "USD" | "EUR" | "GOLD";
            /**
             * @description Hedefi temsil eden emoji/ikon
             * @example 💻
             */
            icon?: string;
            /**
             * @description Arayüzde gösterilecek renk (Hex)
             * @example #33FF57
             */
            color?: string;
        };
        RegisterDto: {
            /**
             * @description Kullanıcının e-posta adresi
             * @example haktan@nexuscore.com
             */
            email: string;
            /**
             * @description En az 6 karakterli şifre
             * @example S3cr3tP@ss!
             */
            password: string;
            /**
             * @description Kullanıcının adı
             * @example X
             */
            firstName: string;
            /**
             * @description Kullanıcının soyadı
             * @example Y
             */
            lastName: string;
        };
        LoginDto: {
            /**
             * @description Kayıtlı e-posta adresiniz
             * @example x@y.com
             */
            email: string;
            /**
             * @description Şifreniz
             * @example S3cr3tP@ss!
             */
            password: string;
        };
        LoggedInUserDto: {
            /**
             * @description Kullanıcı ID
             * @example uuid-string
             */
            id: string;
            /** @example ahmet@test.com */
            email: string;
            /** @example Ahmet */
            firstName: string;
            /** @example Yılmaz */
            lastName: string;
            /**
             * @example FREE
             * @enum {string}
             */
            role: "FREE" | "PLUS" | "ADMIN";
            /**
             * @description Kullanıcının yetkilerini ve limitlerini belirten Frontend UI konfigürasyonu. Arayüzdeki butonları gizlemek/göstermek için kullanılır.
             * @example {
             *       "canDeleteTransactions": false,
             *       "canManageSystemTags": false,
             *       "maxAccountsLimit": 3,
             *       "maxGoalsLimit": 2
             *     }
             */
            config: Record<string, never>;
        };
        LoginResponseDto: {
            /**
             * @description Bütün API isteklerinde Authorization: Bearer <token> formatında kullanılacak şifreli anahtar.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
            /** @description Giriş yapan kullanıcının temel bilgileri ve UI yetkileri. */
            user: components["schemas"]["LoggedInUserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AccountController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hesapların listesi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"][];
                };
            };
        };
    };
    AccountController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDto"];
            };
        };
        responses: {
            /** @description Hesap başarıyla oluşturuldu. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
        };
    };
    AccountController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hesap detayı. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
        };
    };
    AccountController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silme işlemi sonucu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    AccountController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountDto"];
            };
        };
        responses: {
            /** @description Hesap başarıyla güncellendi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
        };
    };
    CategoryController_findAll: {
        parameters: {
            query?: {
                /** @description Sadece belirli bir türdeki kategorileri getirmek için */
                type?: "INCOME" | "EXPENSE" | "TRANSFER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"][];
                };
            };
        };
    };
    CategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"];
                };
            };
        };
    };
    CategoryController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kategori ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"];
                };
            };
        };
    };
    CategoryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Silinecek Kategori ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silme işlemi sonucu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    CategoryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Güncellenecek Kategori ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"];
                };
            };
        };
    };
    TransactionController_findAll: {
        parameters: {
            query?: {
                /** @description Sayfa numarası */
                page?: number;
                /** @description Sayfa başı kayıt sayısı */
                limit?: number;
                /** @description Sıralanacak kolon (Örn: createdAt, date) */
                sortBy?: string;
                /** @description Sıralama yönü */
                sortOrder?: "ASC" | "DESC";
                /** @description Başlangıç tarihi (ISO Format) */
                startDate?: string;
                /** @description Bitiş tarihi (ISO Format) */
                endDate?: string;
                /** @description İşlem Tipi */
                type?: "INCOME" | "EXPENSE" | "TRANSFER";
                /** @description Belirli bir kategoriye ait işlemler */
                categoryId?: string;
                /** @description Belirli bir hesaba ait işlemler */
                accountId?: string;
                /** @description Sadece düzenli (tekrarlayan) veya tek seferlik işlemleri filtreler */
                isRecurring?: boolean;
                /** @description Excel dosyasının dili (Varsayılan: tr) */
                lang?: "tr" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sayfalanmış işlem listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionDto"];
            };
        };
        responses: {
            /** @description İşlem başarıyla oluşturuldu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
        };
    };
    TransactionController_findRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Düzenli ödeme listesi başarıyla getirildi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"][];
                };
            };
        };
    };
    TransactionController_cancelRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description İptal edilecek düzenli ödeme ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    TransactionController_deleteInstallmentGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Silinmek istenen taksit grubunun benzersiz ID'si */
                installmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    TransactionController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Silinmek istenen işlemin ID'si */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    TransactionController_export: {
        parameters: {
            query?: {
                /** @description Sayfa numarası */
                page?: number;
                /** @description Sayfa başı kayıt sayısı */
                limit?: number;
                /** @description Sıralanacak kolon (Örn: createdAt, date) */
                sortBy?: string;
                /** @description Sıralama yönü */
                sortOrder?: "ASC" | "DESC";
                /** @description Başlangıç tarihi (ISO Format) */
                startDate?: string;
                /** @description Bitiş tarihi (ISO Format) */
                endDate?: string;
                /** @description İşlem Tipi */
                type?: "INCOME" | "EXPENSE" | "TRANSFER";
                /** @description Belirli bir kategoriye ait işlemler */
                categoryId?: string;
                /** @description Belirli bir hesaba ait işlemler */
                accountId?: string;
                /** @description Sadece düzenli (tekrarlayan) veya tek seferlik işlemleri filtreler */
                isRecurring?: boolean;
                /** @description Excel dosyasının dili (Varsayılan: tr) */
                lang?: "tr" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlannedPaymentController_findAll: {
        parameters: {
            query?: {
                /** @description Odeme durumu filtrelemesi */
                isPaid?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedPaymentResponseDto"][];
                };
            };
        };
    };
    PlannedPaymentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlannedPaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedPaymentResponseDto"];
                };
            };
        };
    };
    PlannedPaymentController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedPaymentResponseDto"];
                };
            };
        };
    };
    PlannedPaymentController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    PlannedPaymentController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlannedPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedPaymentResponseDto"];
                };
            };
        };
    };
    PlannedPaymentController_pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedPaymentResponseDto"];
                };
            };
        };
    };
    NotificationController_findAll: {
        parameters: {
            query?: {
                /** @description Sadece okunmamis bildirimler */
                onlyUnread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"][];
                };
            };
        };
    };
    NotificationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    NotificationController_markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    NotificationController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    NotificationController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    NotificationController_markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    DashboardController_getSummary: {
        parameters: {
            query?: {
                /** @description Örn: 2026 (Varsayılan: İçinde bulunulan yıl) */
                year?: number;
                /** @description Örn: 3 (Varsayılan: İçinde bulunulan ay) */
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getHealthScore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı hesaplama sonucu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialHealthResponseDto"];
                };
            };
        };
    };
    TagController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponseDto"][];
                };
            };
        };
    };
    TagController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponseDto"];
                };
            };
        };
    };
    TagController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponseDto"];
                };
            };
        };
    };
    TagController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Silinecek Etiket ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    TagController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponseDto"];
                };
            };
        };
    };
    GoalController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponseDto"][];
                };
            };
        };
    };
    GoalController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponseDto"];
                };
            };
        };
    };
    GoalController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponseDto"];
                };
            };
        };
    };
    GoalController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Silinecek Hedef ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeleteResponseDto"];
                };
            };
        };
    };
    GoalController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponseDto"];
                };
            };
        };
    };
    UserController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getVipReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Giriş başarılı. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
}
